### ISSUE TITLE
Error on opening dmg for MacOS

### ISSUE THREAD

**Issue by nwoodfine** [ElementsProject/elements#666] opened 2019-06-17 14:08 UTC
Upon opening liquid-0.17.0-osx-unsigned.dmg, system hangs, then get error: `The document “Elements-Core” could not be opened. Finder cannot open files in the “volume`

Had to manually check the drive had been mounted, then drag to applications.

Error seems to be inherited from Bitcoin Core: https://www.reddit.com/r/Bitcoin/comments/9lu5vb/can_not_able_to_install_bitcoin_core_on_my_macos/

Should have been shown a finder window showing the mounted drive with app + Applications shortcut after the dmg had been opened.

Got error on first run, not on second run. Neither provided open mounted drive. Took a long while for the error to show. 

liquid-0.17.0-osx-unsigned.dmg

MacBook Air 2013, MacOS

**Comment by instagibbs** [comment] 2019-06-17 14:10
If you can try to compile master(which is ~0.18), maybe see if it was fixed since then?

**Comment by philippem** [comment] 2020-01-04 00:08
I was unable to reproduce this issue with the later release https://github.com/ElementsProject/elements/releases/download/elements-0.18.1.3/elements-0.18.1.3-osx-unsigned.dmg

Double clicking on the dmg file in the finder opens 
![image](https://user-images.githubusercontent.com/565792/71756064-8a3a0980-2e42-11ea-9647-c5259a35cc62.png)


Note that this exhibits a bug whose fix will be included in a subsequent release https://github.com/ElementsProject/elements/pull/798

**Comment by instagibbs** [comment] 2020-01-06 20:41
closing as fixed

**Closed by instagibbs** 2020-01-06 20:41 UTC
