### ISSUE TITLE
OS X build failure

### ISSUE THREAD

**Issue by jlopp** [ElementsProject/elements#11] opened 2015-06-09 20:56 UTC
I have all the dependencies for bitcoind installed and successfully built it, but when trying to build elements it fails with the following error:

```
Undefined symbols for architecture x86_64:
  "IsConfirmedBitcoinBlock(uint256 const&, int)", referenced from:
      TransactionSignatureChecker::IsConfirmedBitcoinBlock(uint256 const&, bool) const in libalphaconsensus_la-interpreter.o
  "CHMAC_SHA256::CHMAC_SHA256(unsigned char const*, unsigned long)", referenced from:
      EvalScript(std::__1::vector<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, std::__1::allocator<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > >&, CScript const&, unsigned int, BaseSignatureChecker const&, ScriptError_t*) in libalphaconsensus_la-interpreter.o
  "_SSL_library_init", referenced from:
      boost::asio::ssl::detail::openssl_init_base::do_init::do_init() in libalphaconsensus_la-interpreter.o
  "CHMAC_SHA256::Finalize(unsigned char*)", referenced from:
      EvalScript(std::__1::vector<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, std::__1::allocator<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > >&, CScript const&, unsigned int, BaseSignatureChecker const&, ScriptError_t*) in libalphaconsensus_la-interpreter.o
  "CheckBitcoinProof(CBlockHeader const&)", referenced from:
      EvalScript(std::__1::vector<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, std::__1::allocator<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > >&, CScript const&, unsigned int, BaseSignatureChecker const&, ScriptError_t*) in libalphaconsensus_la-interpreter.o
  "GetScriptForDestination(boost::variant<CNoDestination, CKeyID, CScriptID, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&)", referenced from:
      EvalScript(std::__1::vector<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, std::__1::allocator<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > >&, CScript const&, unsigned int, BaseSignatureChecker const&, ScriptError_t*) in libalphaconsensus_la-interpreter.o
  "GetBoolArg(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool)", referenced from:
      EvalScript(std::__1::vector<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, std::__1::allocator<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > >&, CScript const&, unsigned int, BaseSignatureChecker const&, ScriptError_t*) in libalphaconsensus_la-interpreter.o
  "CPartialMerkleTree::CPartialMerkleTree()", referenced from:
      EvalScript(std::__1::vector<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, std::__1::allocator<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > >&, CScript const&, unsigned int, BaseSignatureChecker const&, ScriptError_t*) in libalphaconsensus_la-interpreter.o
  "CheckProof(CBlockHeader const&)", referenced from:
      EvalScript(std::__1::vector<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, std::__1::allocator<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > >&, CScript const&, unsigned int, BaseSignatureChecker const&, ScriptError_t*) in libalphaconsensus_la-interpreter.o
  "boost::system::system_category()", referenced from:
      __GLOBAL__sub_I_script.cpp in libalphaconsensus_la-script.o
      boost::asio::ssl::detail::openssl_init_base::do_init::do_init() in libalphaconsensus_la-interpreter.o
      ___cxx_global_var_init62 in libalphaconsensus_la-interpreter.o
      ___cxx_global_var_init65 in libalphaconsensus_la-interpreter.o
      __GLOBAL__sub_I_interpreter.cpp in libalphaconsensus_la-interpreter.o
  "CBlockHeader::GetHash() const", referenced from:
      EvalScript(std::__1::vector<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, std::__1::allocator<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > >&, CScript const&, unsigned int, BaseSignatureChecker const&, ScriptError_t*) in libalphaconsensus_la-interpreter.o
  "_SSL_load_error_strings", referenced from:
      boost::asio::ssl::detail::openssl_init_base::do_init::do_init() in libalphaconsensus_la-interpreter.o
  "CPartialMerkleTree::ExtractMatches(std::__1::vector<uint256, std::__1::allocator<uint256> >&)", referenced from:
      EvalScript(std::__1::vector<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, std::__1::allocator<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > >&, CScript const&, unsigned int, BaseSignatureChecker const&, ScriptError_t*) in libalphaconsensus_la-interpreter.o
  "CScriptID::CScriptID(CScript const&)", referenced from:
      EvalScript(std::__1::vector<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, std::__1::allocator<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > >&, CScript const&, unsigned int, BaseSignatureChecker const&, ScriptError_t*) in libalphaconsensus_la-interpreter.o
  "boost::system::generic_category()", referenced from:
      __GLOBAL__sub_I_script.cpp in libalphaconsensus_la-script.o
      __GLOBAL__sub_I_interpreter.cpp in libalphaconsensus_la-interpreter.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libalphaconsensus.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**Comment by gwillen** [comment] 2015-06-09 21:09
This is the exact same error I was getting, building this on my OS X machine. It doesn't seem to happen to everyone, but since I seem to get it reproducibly, I'll investigate.

**Comment by jlopp** [comment] 2015-06-09 21:12
FYI I'm on OS X 10.10.3 with an Intel Core i5 CPU.

**Comment by gwillen** [comment] 2015-06-09 21:16
For the record I'm on 10.9.4. My error spew is not identical but I think it might just be a reordering of the same lines.

**Comment by gwillen** [comment] 2015-06-09 21:53
Note that these errors are all while building `libbitcoin_consensus`, which I don't *think* anything interesting actually depends on. So a workaround might be just to make `src/alphad` and (if desired) `src/alpha-cli`. (When I build `alphad` I get a _different_ link error, related to Boost, which I'm investigating. Let me know whether it works for you.)

**Comment by jlopp** [comment] 2015-06-09 22:03
Confirmed that "make src/alphad" and "make src/alpha-cli" build successfully

**Comment by gwillen** [comment] 2015-06-11 06:16
I'm going to close this; the consensus lib build is still flaky for mysterious reasons, but it's now off by default, and I'm not aware of anybody needing it to build in this tree.

**Comment by gwillen** [comment] 2015-06-11 06:16
(PS: Thanks for your help @jlopp!)

**Closed by gwillen** 2015-06-11 06:16 UTC

**Comment by noamher** [comment] 2015-10-01 12:20
@gwillen I've tried compiling with --with-libs=yes on osx and I noticed the error is still there.
I'm trying to compile the consensus lib specifically and would prefer to do it on osx (rather then linux) if possible.
just to let you know somebody wants to use the --with-libs=yes on osx.
