### ISSUE TITLE
Creating a transaction with too many inputs crashes QT

### ISSUE THREAD

**Issue by Kukks** [ElementsProject/elements#979] opened 2021-04-02 07:41 UTC
When using Elements QT to create a transaction with >200inputs, QT crashes.  Constructing a transaction with less inpuits works correctly.

Show an error instead of crashing

Application crashes.

Create a transaction with more inputs than max

elements-0.18.1.11 (64-bit) from https://github.com/ElementsProject/elements/releases/download/elements-0.18.1.11/elements-0.18.1.11-win64-setup-unsigned.exe

Windows 10 Pro x64 with SSD

Running `sendtoaddress` on cli provides an error message instead of a crash. This seems purely related to the GUI.

Could not see any logs indicating an error message apart from 
`"registerShutdownBlockReason: Successfully registered: Elements Core didn't yet exit safely..."`

**Comment by apoelstra** [comment] 2021-04-21 13:16
I believe this is a dupe of https://github.com/ElementsProject/elements/issues/880 -- we intend to fix this in the upcoming 0.21 release.

Thank you for reporting it.

**Closed** 2021-08-30 20:56 UTC
